### ISSUE TITLE
Consider uglify-es by default

### ISSUE THREAD

**Issue by tomkel** [TrySound/rollup-plugin-uglify#34]
Webpack uglify plugin just started using uglify-es by default.

https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/63

**Comment by TrySound** [comment]
PR welcome

**Comment by paulocoghi** [comment]
@TrySound, since uglify-es represents the UglifyJS version 3, and its API is not backward compatible with version 2, it would be interesting to test it before merge (apparently the tests passed).

**Comment by TrySound** [comment]
This project uses uglify3

**Comment by paulocoghi** [comment]
Nice, thanks! In this case, is that [PR](https://github.com/TrySound/rollup-plugin-uglify/pull/35) apt to be approved?

**Comment by VincentCharpentier** [comment]
Seems like ES6 is still an issue with this plugin. 
Am I missing a newer plugin that should replace this one ?

The trick mentioned above is not longer possible:

```javascript
uglify({}, minify) // This won't work
```

The uglify function takes only one `options` argument now

I tried @babel/preset-env with `forceAllTransforms: true` because the docs says:

> Enable this option if you want to force running all transforms, which is useful if the output will be run through UglifyJS or an environment that only supports ES5.

But it's not working so far

**Comment by TrySound** [comment]
Yes, use this one https://github.com/TrySound/rollup-plugin-terser.
![image](https://user-images.githubusercontent.com/5635476/76640844-af917500-6561-11ea-87b1-b800b1c7ee30.png)

**Comment by VincentCharpentier** [comment]
Thanks for the quick reply, works really well now 👍
